### ISSUE TITLE
Possible delete of an object due reading from MongoDB

### ISSUE THREAD

**Issue by naiyerasif** [Microflash/guides#1]
In GitLab by @CyberpunkPerson on Oct 24, 2020, 07:44

In [CascadeMongoEventListener](https://gitlab.com/mflash/spring-guides/-/blob/master/spring-data-mongo-repository/src/main/java/dev/mflash/guides/mongo/helper/event/CascadeMongoEventListener.java) `onAfterConvert` event could be invoke during reading what is leads that objects could be deleted due reading

Example:
1. get (something) by id method in repository has been invoked
2. `onAfterConvert` has been invoked
3. child objects have been deleted
4. game over

**Comment by naiyerasif** [comment]
In GitLab by @Microflash on Oct 24, 2020, 11:24

assigned to @Microflash

**Comment by naiyerasif** [comment]
In GitLab by @Microflash on Oct 24, 2020, 11:26

That's actually correct. I'm planning to revisit that implementation and provide some updates this weekend. Thanks for pointing this out.

**Comment by naiyerasif** [comment]
Fixed in 123ade53bc56d094be964f5fb48679f8a197082c

**Comment by CyberpunkPerson** [comment]
Hi, naiyerasif. It's up to you, of course, but by this commit you broke `Service Stateless Principle` which in you case leads to data inconsistency 😊

**Comment by naiyerasif** [comment]
I am aware of that as well since I've to resort to store `deletedAccount` across the lifecycle. The guide was supposed to showcase how the cascading could be done, if needed. Any attempt to do so will fail one way or the other as long as it not natively supported 😄 I will add a warning in that implementation explicitly mentioning the problem it may cause with state.

**Comment by CyberpunkPerson** [comment]
As I said it's up to you, it's your guide anyway. I looked for solution before I saw your's and did not find anything decent. Moreover even extending and overriding of existed Mongo components impossible, because of bad design of Mongo developers. Mongo components can be extended, but methods can not be overridden, because parameters  have package private modificators.
